IspitMVCProjekat/Controllers/IspitiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IspitMVCProjekat.Models;
using IspitMVCProjekat.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace IspitMVCProjekat.Controllers
{
    public class IspitiController : Controller
    {
        private I_IspitRepository _repo;

        public IspitiController(I_IspitRepository repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            var ispiti = _repo.Index();

            return View(ispiti);

        }



        public IActionResult Create()
        {

            ViewBag.Student = _repo.StudentiToList();
            ViewBag.Predmet = _repo.PredmetiToList();

            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("IspitId, BrojIndexa, PredmetId, Ocena")] Ispit ispit, string Student, string Predmet)
        {


            _repo.Create(ispit, Student, Predmet);

            if (ispit.BrojIndexa == null || ispit.PredmetId == 0)
            {
                return View("ErrorIspit");
            }

            return RedirectToAction(nameof(Index));

        }


        public ViewResult Edit(int? IspitID)
        {
            var ispit = _repo.GetElementById(IspitID);

            if (IspitID == null || ispit == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml");
            }

            ViewBag.Student = _repo.StudentiToList();
            ViewBag.Predmet = _repo.PredmetiToList();

            return View(ispit);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("IspitId, BrojIndexa, PredmetId, Ocena")] Ispit ispit, string Student, string Predmet)
        {
            if (ispit.IspitId == 0)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                _repo.Edit(ispit, Student, Predmet);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View("ErrorIspit");

            }


            return View(ispit);
        }


        public ViewResult Details(int? IspitID)
        {
            var ispit = _repo.GetElementById(IspitID);

            if (IspitID == null || ispit == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml");
            }


            return View(ispit);
        }



        public ViewResult Delete(int? IspitID)
        {
            var ispit = _repo.GetElementById(IspitID);

            if (IspitID == null || ispit == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml");
            }

            return View(ispit);
        }


        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Ispit ispit)
        {
            _repo.DeleteConfirmed(ispit);
            return RedirectToAction(nameof(Index));
        }

    }
}

IspitMVCProjekat/Controllers/PredmetiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IspitMVCProjekat.Models;
using IspitMVCProjekat.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IspitMVCProjekat.Controllers
{
    public class PredmetiController : Controller
    {
        private IPredmetRepository _repo;

        

        public PredmetiController(IPredmetRepository repo)
        {
            
            _repo = repo;
        }
        public IActionResult Index()
        {
            var predmeti = _repo.Index();

            return View(predmeti);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PredmetId, ImePredmeta")] Predmet predmet)
        {
            if (ModelState.IsValid)
            {
                if (!_repo.PredmetExists(predmet.ImePredmeta))
                {
                    _repo.Create(predmet);
                    return RedirectToAction(nameof(Index));
                }   
            }
            return View("ErrorInsertingPredmet");
        }


        public ViewResult Details(int? PredmetID)
        {
            var predmet = _repo.Details(PredmetID);

            if (PredmetID == null || predmet == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml");
            }

            return View(predmet);
        }


        public ViewResult Edit(int? PredmetID)
        {
            var predmet = _repo.Edit(PredmetID);

            if (PredmetID == null || predmet == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml");
            }

            return View(predmet);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("PredmetId,ImePredmeta")] Predmet predmet)
        {
            if (predmet.PredmetId == 0)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _repo.Edit(predmet);   
            }

            return RedirectToAction(nameof(Index));
        }


        public ViewResult Delete(int? PredmetID)
        {
            var predmet = _repo.Delete(PredmetID);

            if (PredmetID == null || predmet == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml");
            }


            return View(predmet);
        }




        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int PredmetID)
        {
            _repo.DeleteConfirmed(PredmetID);

            return RedirectToAction(nameof(Index));
        }




    }
}

IspitMVCProjekat/Controllers/StudentiController.cs
using System;
using IspitMVCProjekat.Models;
using IspitMVCProjekat.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace IspitMVCProjekat.Controllers
{
    public class StudentiController : Controller
    {
        private IStudentRepository _repo;

        public StudentiController(IStudentRepository repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            var studenti = _repo.Index();


            return View(studenti);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("BrojIndexa,Ime,Prezime,Adresa,Grad")] Student student)
        {
            if(_repo.StudentExists(student.BrojIndexa))
            {
                ModelState.AddModelError("","Broj indexa vec postoji");
            }

            if (ModelState.IsValid)
            {
                    _repo.Create(student);
                    return RedirectToAction(nameof(Index));

            }
            
            return View();

        }




        public ViewResult Edit(string brIndexa)
        {
            var student = _repo.Edit(brIndexa);

            if (brIndexa == null || student == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml");
            }

            return View(student);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("BrojIndexa,Ime,Prezime,Adresa,Grad")] Student student)
        {
            if (student.BrojIndexa == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _repo.Edit(student);

            }
            return RedirectToAction(nameof(Index));
        }


        public ViewResult Delete(string brIndexa)
        {
            var SelectedStudent = _repo.Delete(brIndexa);

            if (brIndexa == null || SelectedStudent == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml"); ;
            }


            return View(SelectedStudent);
        }


        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Student student)
        {
            _repo.DeleteConfirmed(student);
            return RedirectToAction(nameof(Index));
        }




        public ViewResult Details(string brIndexa)
        {
            var student = _repo.Details(brIndexa);

            if (brIndexa == null || student == null)
            {
                return View("~/Views/Shared/ErrNotFound.cshtml");
            }

            ViewBag.Ispiti = _repo.Query(brIndexa);

            return View(student);

        }


        public new void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }









    }
}

IspitMVCProjekat/Views/Shared/ErrNotFound.cshtml
<p>
    Content not found
</p>

IspitMVCProjekat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IspitiApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" type="text/css"href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IspitMVCProjekat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Predmeti" asp-action="Index">Predmeti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Studenti" asp-action="Index">Studenti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ispiti" asp-action="Index">Ispiti</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div class="container">
                &copy; 2020 - IspitMVCProjekat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootbox.js/bootbox.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.js">
    </script>
    @*DATATABLES*@
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>